"""Central defaults for local UI, CLI, and business-service testing."""

DEFAULT_MODEL_DIR = "meituan-longcat/LongCat-AudioDiT-3.5B"
DEFAULT_DEVICE = None
DEFAULT_LANGUAGE = "en"

DEFAULT_ODE_STEPS = 16
DEFAULT_GUIDANCE_METHOD = "cfg"
DEFAULT_GUIDANCE_STRENGTH = 4.0
DEFAULT_SPEECH_RATE = 1.3

DEFAULT_TARGET_SEGMENT_SECONDS = 20
DEFAULT_MAX_SEGMENT_SECONDS = 25
MAX_GENERATION_SECONDS = 180
SEGMENT_SLIDER_MAX_SECONDS = 180

DEFAULT_MP3_BITRATE = "192k"
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 7860

BOUNDARY_PAUSES = {
    "paragraph": 0.10,
    "sentence": 0.10,
    "clause": 0.09,
    "word": 0.05,
}
