"""Central defaults for local UI, CLI, and business-service testing."""

DEFAULT_MODEL_DIR = "meituan-longcat/LongCat-AudioDiT-3.5B"
DEFAULT_DEVICE = None
DEFAULT_LANGUAGE = "en"

DEFAULT_ODE_STEPS = 16
DEFAULT_GUIDANCE_METHOD = "cfg"
DEFAULT_GUIDANCE_STRENGTH = 4.0
DEFAULT_SPEECH_RATE = 1.25

DEFAULT_TARGET_SEGMENT_SECONDS = 50
DEFAULT_MAX_SEGMENT_SECONDS = 60
MAX_GENERATION_SECONDS = 180
SEGMENT_SLIDER_MAX_SECONDS = 180

DEFAULT_MP3_BITRATE = "192k"
DEFAULT_SEED = 1024
DEFAULT_FADE_SECONDS = 0.0
DEFAULT_HOST = "0.0.0.0"
DEFAULT_PORT = 7860

DEFAULT_API_PORT = 7861
DEFAULT_API_DATA_DIR = "data/longcat_api"
DEFAULT_RESULT_TTL_HOURS = 24.0
DEFAULT_CLEANUP_INTERVAL_SECONDS = 300.0
DEFAULT_MAX_PENDING_TASKS = 20

REFERENCE_UPLOAD_CHUNK_BYTES = 1024 * 1024
MAX_REFERENCE_UPLOAD_BYTES = 50 * 1024 * 1024
MAX_REFERENCE_DURATION_SECONDS = 60.0
MAX_REFERENCE_TEXT_CHARS = 10_000
MAX_GENERATION_TEXT_CHARS = 2_000_000

BOUNDARY_PAUSES = {
    "paragraph": 0.00,
    "sentence": 0.00,
    "clause": 0.00,
    "word": 0.00,
}
